# Generated by Django 2.2.4 on 2019-08-09 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of analysis', max_length=30, unique=True)),
                ('description', models.CharField(help_text='Description', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('typ', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of material', max_length=30, unique=True)),
                ('typ', models.PositiveSmallIntegerField(default=0, help_text='Type of material, 0 for default')),
                ('viscosity', models.FloatField(default=0, help_text='Enter a number for viscosity')),
                ('permeability', models.FloatField(default=0, help_text='Enter a number for permeability')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material', to='analyses.Analysis')),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step', to='analyses.Analysis')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section', to='analyses.Analysis')),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material', to='analyses.Material')),
            ],
        ),
        migrations.CreateModel(
            name='Mesh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of mesh', max_length=30, unique=True)),
                ('address', models.FileField(upload_to='meshfiles/')),
                ('analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mesh', to='analyses.Analysis')),
            ],
        ),
    ]
