# Generated by Django 2.2.4 on 2019-09-13 05:34

import analyses.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of analysis (do not use space)', max_length=30, unique=True)),
                ('description', models.CharField(help_text='Description', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Mesh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='_None', max_length=100)),
                ('address', models.FileField(help_text='The layout should be primarily in x-y plane.', upload_to=analyses.models.analysis_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['unv'])])),
                ('NumFaces', models.IntegerField(default=1)),
                ('NumEdges', models.IntegerField(default=1)),
                ('analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mesh', to='analyses.Analysis')),
            ],
        ),
        migrations.CreateModel(
            name='Preform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of Preform', max_length=30)),
                ('thickness', models.FloatField(default=0.01, help_text='Thickness')),
                ('K11', models.FloatField(default=1e-10, help_text='Enter a number for K11')),
                ('K12', models.FloatField(default=0, help_text='Enter a number for K12')),
                ('K22', models.FloatField(default=2e-10, help_text='Enter a number for K22')),
                ('phi', models.FloatField(default=0.5, help_text='Enter a number for volume fraction')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preform', to='analyses.Analysis')),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('typ', models.CharField(choices=[('Fill everywhere', 'Fill everywhere'), ('Fill the outlet', 'Fill the outlet')], max_length=30)),
                ('endtime', models.FloatField()),
                ('outputstep', models.FloatField()),
                ('maxiterations', models.IntegerField()),
                ('maxhaltsteps', models.IntegerField()),
                ('minchangesaturation', models.FloatField()),
                ('timescaling', models.FloatField()),
                ('fillthreshold', models.FloatField()),
                ('analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='step', to='analyses.Analysis')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('rotate', models.FloatField(default=0, help_text='Degree of rotation of 1st axis with respect to x axis')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section', to='analyses.Analysis')),
                ('preform', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preform', to='analyses.Preform')),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processID', models.CharField(default=0, max_length=30)),
                ('analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='analyses.Analysis')),
            ],
        ),
        migrations.CreateModel(
            name='Resin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of Resin', max_length=30)),
                ('viscosity', models.FloatField(help_text='Enter a number for viscosity')),
                ('analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resin', to='analyses.Analysis')),
            ],
        ),
        migrations.CreateModel(
            name='Nodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NodeNum', models.IntegerField()),
                ('x', models.FloatField(max_length=6, null=True)),
                ('y', models.FloatField(max_length=6, null=True)),
                ('z', models.FloatField(max_length=6, null=True)),
                ('FaceGroup', models.CharField(default='_None', max_length=50)),
                ('EdgeGroup', models.CharField(default='_None', max_length=50)),
                ('mesh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyses.Mesh')),
            ],
        ),
        migrations.CreateModel(
            name='Connectivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ElmNum', models.IntegerField(null=True)),
                ('N1', models.IntegerField(null=True)),
                ('N2', models.IntegerField(null=True)),
                ('N3', models.IntegerField(null=True)),
                ('mesh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyses.Mesh')),
            ],
        ),
        migrations.CreateModel(
            name='BC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('typ', models.CharField(choices=[('Wall', 'Wall'), ('Inlet', 'Inlet'), ('Outlet', 'Outlet')], default=0, max_length=30)),
                ('condition', models.CharField(choices=[('Pressure', 'Pressure'), ('Flow rate', 'Flow rate'), ('None', 'None')], default=0, max_length=30)),
                ('value', models.FloatField(default=0, help_text='Value on Boundary Condition')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bc', to='analyses.Analysis')),
            ],
        ),
    ]
